---

name: Manaul trigger with locales PR
on:
  workflow_dispatch:
      inputs:
        SYNC_TERMS:
          description: 'Remove unused labels'     
          required: false
          default: 'false'

jobs:

  Setup:
    runs-on: ubuntu-latest
    outputs:
      COMMIT_TO: ${{ env.COMMIT_TO }}
      TEMP_BRANCH: ${{ env.TEMP_BRANCH }}
      ENVIRONMENT: ${{ env.ENVIRONMENT }}
      CURRENT_DATE: ${{ env.CURRENT_DATE }}
      SYNC_TERMS: ${{ env.SYNC_TERMS }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if its DEV repo
        if: github.repository_owner != 'ProteGO-Safe'
        run: |
          echo "ENVIRONMENT=DEV" >> $GITHUB_ENV

      - name: Set ENV's
        run: |
            echo "TEMP_BRANCH=translations/POE-$(date +'%Y-%m-%d%H%M')" >> $GITHUB_ENV
            echo "COMMIT_TO=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
            echo "CURRENT_DATE=$(date +'%Y-%m-%d_%H:%M')" >> $GITHUB_ENV
            echo "SYNC_TERMS=${{ github.event.inputs.SYNC_TERMS }}" >> $GITHUB_ENV
        shell: bash
  
  POE_SYNC_TERMS:
    runs-on: ubuntu-latest
    needs: [Setup]
    if: needs.Setup.outputs.ENVIRONMENT == 'DEV' && needs.Setup.outputs.SYNC_TERMS == 'true'
    env:
      COMMIT_TO: ${{ needs.Setup.outputs.COMMIT_TO }}
      TEMP_BRANCH: ${{ needs.Setup.outputs.TEMP_BRANCH }}
      SYNC_TERMS: ${{ needs.Setup.outputs.SYNC_TERMS }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.COMMIT_TO }}

      - name: Sync terms from PL file
        run: |
          sh locales/scripts/sync_terms.sh -i ${{ secrets.POEDITOR_ID }} -t ${{ secrets.POEDITOR_TOKEN }} -o locales

  POE_CHECK_UPDATE:
    runs-on: ubuntu-latest
    needs: [Setup]
    if: needs.Setup.outputs.ENVIRONMENT == 'DEV' && needs.Setup.outputs.SYNC_TERMS == 'false'
    outputs: 
      UPGRADE: ${{ env.UPGRADE }}
    env:
      COMMIT_TO: ${{ needs.Setup.outputs.COMMIT_TO }}
      TEMP_BRANCH: ${{ needs.Setup.outputs.TEMP_BRANCH }}
      SYNC_TERMS: ${{ needs.Setup.outputs.SYNC_TERMS }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.COMMIT_TO }}

      - name: Download REMOTE LOCALES from POEditor
        run: |
          for l in $(find locales -type f -maxdepth 1 -name "*.json" -exec basename {} .json ';')
          do
            echo "Processing $l"
            mv locales/$l.json /tmp/
          	sh  locales/scripts/export.sh  -i ${{ secrets.POEDITOR_ID }} -t ${{ secrets.POEDITOR_TOKEN }} -l $l
            python3 locales/scripts/format_checker.py $l
            if ! diff -q locales/$l.json /tmp/$l.json 2>/dev/null
            then 
              echo "UPGRADE=true" >> $GITHUB_ENV
            fi
          done
        shell: bash

      - uses: fregante/setup-git-user@v1
        if: env.UPGRADE == 'true'

      - name: Git setup new branch
        run: |
            git checkout -b ${{ env.TEMP_BRANCH }}
            git push -u origin ${{ env.TEMP_BRANCH }} -f
        if: env.UPGRADE == 'true'
        
      - uses: actions/upload-artifact@master
        with:
          name: locales
          path: locales/*.json
        if: env.UPGRADE == 'true'

  POE_MAKE_PR:
    runs-on: ubuntu-latest
    needs: [Setup,POE_CHECK_UPDATE]
    if: needs.Setup.outputs.ENVIRONMENT == 'DEV' && needs.Setup.outputs.SYNC_TERMS == 'false' && needs.POE_CHECK_UPDATE.outputs.UPGRADE == 'true'
    env:
      COMMIT_TO: ${{ needs.Setup.outputs.COMMIT_TO }}
      TEMP_BRANCH: ${{ needs.Setup.outputs.TEMP_BRANCH }}
      CURRENT_DATE: ${{ needs.Setup.outputs.CURRENT_DATE }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.TEMP_BRANCH }}

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: locales
          path: locales/

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Locales
          base: ${{ env.COMMIT_TO }}
          branch: ${{ env.TEMP_BRANCH }}
          delete-branch: true
          draft: true
          title: '[LOCALES] Update to ${{ env.CURRENT_DATE }}'
          body: |
            Update locales
          labels: |
            locales
            automated pr
        
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
